### ISSUE TITLE
fft process returns blank image

### ISSUE THREAD

**Issue by icaliskan** [DiegoCatalano/Catalano-Framework#20]
hi, Catalano, fft process returns blank (full wihite) image. where i m doing wrong? i attached code and input, output images.

```
FastBitmap fb = new FastBitmap(imagePath);

Grayscale grayscale = new Grayscale();
grayscale.applyInPlace(fb);
fb.saveAsJPG(path + "grayscale_" + FilenameUtils.getBaseName(imagePath) + ".jpg");

FourierTransform ft = new FourierTransform(fb);
ft.Forward();
fb = ft.toFastBitmap();
fb.saveAsJPG(path + "fft_" + FilenameUtils.getBaseName(imagePath) + ".jpg");

FrequencyFilter ff = new FrequencyFilter(0, 60);
ff.ApplyInPlace(ft);
fb = ft.toFastBitmap();
fb.saveAsJPG(path + "freq_" + FilenameUtils.getBaseName(imagePath) + ".jpg");
```
![slippies](https://cloud.githubusercontent.com/assets/4953268/10312990/27b32f6a-6c56-11e5-9ca7-e8fe306c9077.jpg)
![grayscale_slippies](https://cloud.githubusercontent.com/assets/4953268/10312931/df39d2c0-6c55-11e5-9652-1c06bacff067.jpg)
![fft_slippies](https://cloud.githubusercontent.com/assets/4953268/10312929/df338410-6c55-11e5-8cd8-ad064e27b1e7.jpg)
![freq_slippies](https://cloud.githubusercontent.com/assets/4953268/10312930/df35be6a-6c55-11e5-8497-eeef06a1ae5b.jpg)

**Comment by DiegoCatalano** [comment]
Hello İhsan,
You're probably using an old version. This happen because I have update the fourier transform to work with no power of 2.

I need to release the new version, contains several optimizations and fixes, but you download the master and compile.

With the same code, I got the results below.

![dogs_fourier](https://cloud.githubusercontent.com/assets/5301914/10319766/5d44af42-6c46-11e5-9df7-82e07cce7c9e.jpg)

![dogs_real](https://cloud.githubusercontent.com/assets/5301914/10319787/6ca6baac-6c46-11e5-973c-8804c2a487e1.jpg)

**Comment by icaliskan** [comment]
i solved the problem, thank you. but you can mavenize your project and deploy a repository :D, your libraries will be most usefull.
